export enum JourneyStage {
  AWA_RAIN = "AWA_RAIN",          // Act 1: Rainy Night Awakening
  INVITATION = "INVITATION",      // Act 2: Invitation of Discovery
  FOREST = "FOREST"              // Act 3 & 4: Walking, Catching, Poetic Logging
}

export enum HandGesture {
  OPEN = "OPEN",                 // Five fingers open - Move forward & rotate view
  FIST = "FIST",                 // Hand closed - Grab nearest fireflies & freeze
  OK = "OK",                     // OK gesture - Close index and thumb, others extended
  DOUBLE_OPEN = "DOUBLE_OPEN",   // Double hand open - Dive into the forest, switch to Creek-side scene
  UNKNOWN = "UNKNOWN"
}

export interface Firefly {
  id: string;
  x: number;                     // 0 to 100 within relative viewport
  y: number;                     // 0 to 100 within relative viewport
  z: number;                     // Depth multiplier (0.5 to 1.5) for parallax sizing
  vx: number;
  vy: number;
  hue: number;                   // Glowing color (typically 75-150 for green/yellow-green, occasionally orange-red)
  brightness: number;            // Pulse baseline (0.1 to 1.0)
  pulseSpeed: number;            // Frequency of glowing pulse
  pulsePhase: number;            // Initial phase offset
  glowIntensity: number;         // Dynamic active glow modifier
  isCaptured: boolean;           // True if currently attracted to center of fist
  capturedAt?: number;           // Timestamp when grabbed
}

export interface HandData {
  x: number;                     // Normalized X (0 to 1)
  y: number;                     // Normalized Y (0 to 1)
  gesture: HandGesture;
  confidence: number;            // Gesture confidence score (0 to 1)
}

export interface POELog {
  id: string;
  timestamp: string;             // Display date time (CN locale)
  rawSummary: string;            // The technical natural language summary
  poeticLog: string;             // Beautiful poetic verse generated by Gemini / Fallback
  durationSec: number;           // Duration of observation
  fireflyColor: string;          // Color name in Chinese (e.g. "黄绿","金黄","幽橙")
  isAI: boolean;                 // Whether generated by active Gemini on server
}
